server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:user
#    url: jdbc:h2:~/user
    driver-class-name: org.h2.Driver
    username: root
    password: 123456

security:
  ignored: /worlds/public,/oauth/check_token