server:
  port: 8081
  context-path: /
  servlet-path: /

security:
  user:
    name: user
    password: 123456
  basic:
    enable: false
  oauth2:
#    client:
#      clientId: client
#      clientSecret: secret
#      accessTokenUri: http://localhost:8080/oauth/token
#      grant-type: password
#      scope: app
    resource:
      tokenInfoUri: http://localhost:8080/oauth/check_token