#authserver:
#  hostname: auth-service
#  port: 5000
#  contextPath: /uaa
#
#security:
#  user:
#    name: user
#    password: password
#  oauth2:
#    client:
#      clientId: service1
#      clientSecret: ${security.user.password}
#      accessTokenUri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/oauth/token
#      grant-type: client_credentials
#      scope: server
#    resource:
#      user-info-uri: http://${authserver.hostname}:${authserver.port}${authserver.contextPath}/current